// <auto-generated />
using System;
using ISDQuoter_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISDQuoter_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISDQuoter_API.Models.JobGraphic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorCount")
                        .HasColumnType("int");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("JobGraphics");
                });

            modelBuilder.Entity("ISDQuoter_API.Models.JobQuote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteId"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalPiecePrice")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("GarmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GarmentQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Markup")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("TotalQuotePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("QuoteId");

                    b.HasIndex("GarmentId");

                    b.ToTable("JobQuotes");
                });

            modelBuilder.Entity("ISDQuoter_API.Models.PrintChargeMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorQty")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MaxQty")
                        .HasColumnType("int");

                    b.Property<int>("MinQty")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.ToTable("PrintChargeMatrix");
                });

            modelBuilder.Entity("ISDQuoter_API.Models.Product", b =>
                {
                    b.Property<string>("GarmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GarmentId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ISDQuoter_API.Models.JobGraphic", b =>
                {
                    b.HasOne("ISDQuoter_API.Models.JobQuote", "JobQuote")
                        .WithMany("Graphics")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobQuote");
                });

            modelBuilder.Entity("ISDQuoter_API.Models.JobQuote", b =>
                {
                    b.HasOne("ISDQuoter_API.Models.Product", "Garment")
                        .WithMany("JobQuotes")
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garment");
                });

            modelBuilder.Entity("ISDQuoter_API.Models.JobQuote", b =>
                {
                    b.Navigation("Graphics");
                });

            modelBuilder.Entity("ISDQuoter_API.Models.Product", b =>
                {
                    b.Navigation("JobQuotes");
                });
#pragma warning restore 612, 618
        }
    }
}
